### ISSUE TITLE
Difference to https://github.com/Brotzka/laravel-dotenv-editor

### ISSUE THREAD

**Issue by wowcut** [JackieDo/Laravel-Dotenv-Editor#17]
Hi, nice project - it would be very interesting to read about the main differences between this project and https://github.com/Brotzka/laravel-dotenv-editor - what features does this project provide that does not come with the one mentioned? Thanks!

**Comment by dacoto** [comment]
They are not differences, it's as simple as not including a visual editor, which gives you more freedom to make your own editor and thus you have unnecessary files.
