### ISSUE TITLE
Backup folder is created with autoBackup disabled

### ISSUE THREAD

**Issue by underdpt** [JackieDo/Laravel-Dotenv-Editor#21]
Hi,

I think backup folder should only be checked and created when doing a backup. I have `autoBackup => false` in `app\config\dotenv-editor.php` but backup folder is being created every time I call `DotenvEditor`

**Comment by Sergzy** [comment]
Yeah, it should be created when actual backup method is called, not in constructor.

**Comment by JackieDo** [comment]
> Hi,
> 
> I think backup folder should only be checked and created when doing a backup. I have `autoBackup => false` in `app\config\dotenv-editor.php` but backup folder is being created every time I call `DotenvEditor`

@underdpt , @sergiz : This issue was resolved in pull request #35.
