### ISSUE TITLE
Set Key not working

### ISSUE THREAD

**Issue by tiagomichaelsousa** [JackieDo/Laravel-Dotenv-Editor#24]
When you try to edit the value of a .env key with the $this->editor instantiated in the constructor or with the DotenvEditor facede the value isn't updating in the file.

**Comment by Sergzy** [comment]
I guess you forgot to put ->save() at the end to actually apply changes ;)

**Comment by JackieDo** [comment]
> When you try to edit the value of a .env key with the $this->editor instantiated in the constructor or with the DotenvEditor facede the value isn't updating in the file.

@tiagomichaelsousa : You have to use the `save()` method at the end to actually apply changes (see comment of __sergiz__ on 13 Apr, 2019). This allows you to set the key multiple times continuous and only need to save it once.
