### ISSUE TITLE
Review regex for phpdotenv 3+

### ISSUE THREAD

**Issue by sergejostir** [JackieDo/Laravel-Dotenv-Editor#39]
After https://github.com/JackieDo/Laravel-Dotenv-Editor/pull/37 is merged, someone who has a good knowledge of regex should review this package. Laravel 5.8 started using phpdotenv v3 which introducted some changes how the values are parsed. More info: https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md

**Comment by JackieDo** [comment]
@sergejostir :
The package is being forked and upgraded to version 2.x to be fully compatible with Laravel 9.x and the "vlucas/phpdotenv" package (compatible with parsing method v3+). Please wait for the next few days.

**Comment by JackieDo** [comment]
@sergejostir :
Version 2.zx has been released guys.
