### ISSUE TITLE
Laravel 9 Compatible

### ISSUE THREAD

**Issue by jcmcclorey** [JackieDo/Laravel-Dotenv-Editor#47]
Are there plans to make this package compatible with Laravel 9?

**Comment by JackieDo** [comment]
> Are there plans to make this package compatible with Laravel 9?

Yes, sure. I'm doing it.

**Comment by JackieDo** [comment]
@jcmcclorey :
The package is being forked and upgraded to version 2.x to be fully compatible with Laravel 9.x and the "vlucas/phpdotenv" package. Please wait for the next few days.

**Comment by jcmcclorey** [comment]
Thanks for getting this taken care of

**Comment by jcmcclorey** [comment]
@JackieDo any progress on this?

**Comment by TwIsL** [comment]
So Laravel 9 released. Are there any updates for this?

**Comment by JackieDo** [comment]
@jcmcclorey , @TwIsL :

This package has launched a new version (version 2.x, supports Laravel 9.x also) and already has a release. See [here](https://github.com/JackieDo/Laravel-Dotenv-Editor/releases/tag/2.0.0). Please re-read the [README](https://github.com/JackieDo/Laravel-Dotenv-Editor/blob/master/README.md) carefully.
